[package]
name = "mint_nft"
version = "0.1.0"
edition = "2021"

[dependencies]
near-sdk = { version = "5.5.0", features = ["legacy"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
borsh = "0.9.1"

[lib]
crate-type = ["cdylib"]





